set(BUSYBOX_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/applets/applets.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/ar.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/bbunzip.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/bzip2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/chksum_and_xwrite_tar_header.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/cpio.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/gzip.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/common.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/data_align.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/data_extract_all.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/data_extract_to_command.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/data_extract_to_stdout.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/data_skip.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/decompress_bunzip2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/decompress_gunzip.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/decompress_uncompress.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/decompress_unlzma.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/decompress_unxz.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/filter_accept_all.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/filter_accept_list.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/filter_accept_reject_list.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/find_list_entry.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/get_header_ar.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/get_header_cpio.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/get_header_tar.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/header_list.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/header_skip.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/header_verbose_list.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/init_handle.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/lzo1x_1.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/lzo1x_1o.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/lzo1x_9x.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/lzo1x_d.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/open_transformer.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/seek_by_jump.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/seek_by_read.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/unpack_ar_archive.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/unsafe_prefix.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/libarchive/unsafe_symlink_target.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/lzop.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/tar.c
  ${CMAKE_CURRENT_SOURCE_DIR}/archival/unzip.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/chvt.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/clear.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/deallocvt.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/dumpkmap.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/fgconsole.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/kbd_mode.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/loadfont.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/loadkmap.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/openvt.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/reset.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/resize.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/setconsole.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/setkeycodes.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/setlogcons.c
  ${CMAKE_CURRENT_SOURCE_DIR}/console-tools/showkey.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/basename.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/cat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/chgrp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/chmod.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/chown.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/chroot.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/cksum.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/comm.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/cp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/cut.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/date.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/dd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/df.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/dirname.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/dos2unix.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/du.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/echo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/env.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/expand.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/expr.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/factor.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/false.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/fold.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/head.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/id.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/install.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/libcoreutils/cp_mv_stat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/libcoreutils/getopt_mk_fifo_nod.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/link.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/ln.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/ls.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/md5_sha1_sum.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/mkdir.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/mkfifo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/mknod.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/mktemp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/mv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/nice.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/nl.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/nohup.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/nproc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/od.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/paste.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/printenv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/printf.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/pwd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/readlink.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/realpath.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/rm.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/rmdir.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/seq.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/shred.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/shuf.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/sleep.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/sort.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/split.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/stat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/stty.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/sum.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/sync.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/tac.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/tail.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/tee.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/test.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/test_ptr_hack.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/timeout.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/touch.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/tr.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/true.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/truncate.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/tsort.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/tty.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/uname.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/uniq.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/unlink.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/usleep.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/uudecode.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/uuencode.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/wc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/whoami.c
  ${CMAKE_CURRENT_SOURCE_DIR}/coreutils/yes.c
  ${CMAKE_CURRENT_SOURCE_DIR}/debianutils/pipe_progress.c
  ${CMAKE_CURRENT_SOURCE_DIR}/debianutils/run_parts.c
  ${CMAKE_CURRENT_SOURCE_DIR}/debianutils/start_stop_daemon.c
  ${CMAKE_CURRENT_SOURCE_DIR}/debianutils/which.c
  ${CMAKE_CURRENT_SOURCE_DIR}/e2fsprogs/chattr.c
  ${CMAKE_CURRENT_SOURCE_DIR}/e2fsprogs/e2fs_lib.c
  ${CMAKE_CURRENT_SOURCE_DIR}/e2fsprogs/fsck.c
  ${CMAKE_CURRENT_SOURCE_DIR}/e2fsprogs/lsattr.c
  ${CMAKE_CURRENT_SOURCE_DIR}/e2fsprogs/tune2fs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/editors/awk.c
  ${CMAKE_CURRENT_SOURCE_DIR}/editors/cmp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/editors/diff.c
  ${CMAKE_CURRENT_SOURCE_DIR}/editors/ed.c
  ${CMAKE_CURRENT_SOURCE_DIR}/editors/patch.c
  ${CMAKE_CURRENT_SOURCE_DIR}/editors/sed.c
  ${CMAKE_CURRENT_SOURCE_DIR}/editors/vi.c
  ${CMAKE_CURRENT_SOURCE_DIR}/findutils/find.c
  ${CMAKE_CURRENT_SOURCE_DIR}/findutils/grep.c
  ${CMAKE_CURRENT_SOURCE_DIR}/findutils/xargs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/klibc-utils/nuke.c
  ${CMAKE_CURRENT_SOURCE_DIR}/klibc-utils/resume.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/appletlib.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/ask_confirmation.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/auto_string.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/bb_askpass.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/bb_bswap_64.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/bb_cat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/bb_do_delay.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/bb_getgroups.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/bb_getsockname.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/bb_pwd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/bb_qsort.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/bb_strtonum.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/capability.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/change_identity.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/chomp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/common_bufsiz.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/compare_string_array.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/concat_path_file.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/concat_subpath_file.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/const_hack.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/copy_file.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/copyfd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/correct_password.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/crc32.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/default_error_retval.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/device_open.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/dump.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/duration.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/endofname.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/executable.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/fclose_nonstdin.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/fflush_stdout_and_exit.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/fgets_str.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/find_mount_point.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/find_pid_by_name.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/find_root_device.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/full_write.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/get_console.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/get_cpu_count.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/get_last_path_component.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/get_line_from_file.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/get_shell_name.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/get_volsize.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/getopt32.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/getopt_allopts.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/getpty.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/hash_md5_sha.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/hash_md5_sha256_x86-32_shaNI.S
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/hash_md5_sha256_x86-64_shaNI.S
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/hash_md5_sha_x86-32_shaNI.S
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/hash_md5_sha_x86-64.S
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/hash_md5_sha_x86-64_shaNI.S
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/herror_msg.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/human_readable.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/in_ether.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/inet_cksum.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/inet_common.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/inode_hash.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/isdirectory.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/isqrt.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/iterate_on_dir.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/kernel_version.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/last_char_is.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/lineedit.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/lineedit_ptr_hack.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/llist.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/logenv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/login.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/loop.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/make_directory.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/makedev.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/match_fstype.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/messages.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/missing_syscalls.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/mntent_r.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/mode_string.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/nuke_str.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/parse_config.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/parse_mode.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/percent_decode.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/perror_msg.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/perror_nomsg.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/perror_nomsg_and_die.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/pidfile.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/platform.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/print_flags.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/print_numbered_lines.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/printable.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/printable_string.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/process_escape_sequence.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/procps.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/progress.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/ptr_to_globals.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/pw_encrypt.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/read.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/read_key.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/read_printf.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/recursive_action.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/remove_file.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/replace.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/rtc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/run_shell.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/safe_gethostname.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/safe_poll.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/safe_strncpy.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/safe_write.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/securetty.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/selinux_common.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/semctl.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/setup_environment.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/signals.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/simplify_path.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/single_argv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/skip_whitespace.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/speed_table.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/str_tolower.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/strrstr.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/sysconf.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/time.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/trim.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/u_signal_names.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/ubi.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/udp_io.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/unicode.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/uuencode.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/verror_msg.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/vfork_daemon_rexec.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/warn_ignoring_args.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/wfopen.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/wfopen_input.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/wrap_funcs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/write.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/xatonum.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/xconnect.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/xfunc_die.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/xfuncs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/xfuncs_printf.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/xgetcwd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/xgethostbyname.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/xreadlink.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/xrealloc_vector.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libbb/xregcomp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libpwdgrp/uidgid_get.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/dn_expand.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/dnscruft.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/dnscruft2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/dnscruft3.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/freeaddrinfo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/gai_strerror.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/getaddrinfo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/gethostbyname2_r.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/h_errno.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/res_init.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/res_mkquery.c
  ${CMAKE_CURRENT_SOURCE_DIR}/libres/res_query.c
  ${CMAKE_CURRENT_SOURCE_DIR}/mailutils/mail.c
  ${CMAKE_CURRENT_SOURCE_DIR}/mailutils/makemime.c
  ${CMAKE_CURRENT_SOURCE_DIR}/mailutils/popmaildir.c
  ${CMAKE_CURRENT_SOURCE_DIR}/mailutils/reformime.c
  ${CMAKE_CURRENT_SOURCE_DIR}/mailutils/sendmail.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/adjtimex.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/ascii.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/bbconfig.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/bc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/beep.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/chat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/conspy.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/crond.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/crontab.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/devmem.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/fbsplash.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/flash_eraseall.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/flash_lock_unlock.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/hdparm.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/hexedit.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/inotifyd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/less.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/lsscsi.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/makedevs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/man.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/microcom.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/nandwrite.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/partprobe.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/raidautorun.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/rfkill.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/rx.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/seedrng.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/setfattr.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/setserial.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/strings.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/time.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/tree.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/ts.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/ttysize.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/ubi_tools.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/ubirename.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/volname.c
  ${CMAKE_CURRENT_SOURCE_DIR}/miscutils/watchdog.c
  ${CMAKE_CURRENT_SOURCE_DIR}/modutils/depmod.c
  ${CMAKE_CURRENT_SOURCE_DIR}/modutils/insmod.c
  ${CMAKE_CURRENT_SOURCE_DIR}/modutils/lsmod.c
  ${CMAKE_CURRENT_SOURCE_DIR}/modutils/modinfo.c
  ${CMAKE_CURRENT_SOURCE_DIR}/modutils/modprobe.c
  ${CMAKE_CURRENT_SOURCE_DIR}/modutils/modutils.c
  ${CMAKE_CURRENT_SOURCE_DIR}/modutils/rmmod.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/arp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/arping.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/brctl.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/dnsd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ether-wake.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ether_aton_r.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ether_ntoa_r.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ftpd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ftpgetput.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/hostname.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/httpd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ifconfig.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ifenslave.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ifplugd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ifupdown.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/inetd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/interface.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ip.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ipcalc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/isrv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/isrv_identd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/ip_parse_common_args.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/ipaddress.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/iplink.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/ipneigh.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/iproute.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/iprule.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/iptunnel.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/libnetlink.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/ll_addr.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/ll_map.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/ll_proto.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/ll_types.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/rt_names.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/rtm_map.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/libiproute/utils.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/nameif.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/nbd-client.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/nc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/netstat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/nslookup.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/parse_pasv_epsv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ping.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/pscan.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/route.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/slattach.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/ssl_client.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tcpudp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tcpudp_perhost.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/telnet.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/telnetd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tftp.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tls.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tls_aes.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tls_aesgcm.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tls_fe.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tls_pstm.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tls_pstm_montgomery_reduce.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tls_pstm_mul_comba.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tls_pstm_sqr_comba.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tls_rsa.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tls_sp_c32.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/traceroute.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/tunctl.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/arpping.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/common.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/d6_dhcpc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/d6_packet.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/d6_socket.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/dhcpc.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/dhcpd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/dhcprelay.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/domain_codec.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/dumpleases.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/ifaddrs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/packet.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/signalpipe.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/udhcp/socket.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/vconfig.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/wget.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/whois.c
  ${CMAKE_CURRENT_SOURCE_DIR}/networking/zcip.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/free.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/fuser.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/iostat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/kill.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/lsof.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/mpstat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/nmeter.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/pgrep.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/pidof.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/pmap.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/powertop.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/ps.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/pstree.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/pwdx.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/smemcap.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/sysctl.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/top.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/uptime.c
  ${CMAKE_CURRENT_SOURCE_DIR}/procps/watch.c
  ${CMAKE_CURRENT_SOURCE_DIR}/runit/chpst.c
  ${CMAKE_CURRENT_SOURCE_DIR}/runit/sv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/selinux/chcon.c
  ${CMAKE_CURRENT_SOURCE_DIR}/selinux/getenforce.c
  ${CMAKE_CURRENT_SOURCE_DIR}/selinux/runcon.c
  ${CMAKE_CURRENT_SOURCE_DIR}/selinux/selinuxenabled.c
  ${CMAKE_CURRENT_SOURCE_DIR}/selinux/sestatus.c
  ${CMAKE_CURRENT_SOURCE_DIR}/selinux/setenforce.c
  ${CMAKE_CURRENT_SOURCE_DIR}/shell/ash.c
  ${CMAKE_CURRENT_SOURCE_DIR}/shell/ash_ptr_hack.c
  ${CMAKE_CURRENT_SOURCE_DIR}/shell/cttyhack.c
  ${CMAKE_CURRENT_SOURCE_DIR}/shell/glob.c
  ${CMAKE_CURRENT_SOURCE_DIR}/shell/hush.c
  ${CMAKE_CURRENT_SOURCE_DIR}/shell/match.c
  ${CMAKE_CURRENT_SOURCE_DIR}/shell/math.c
  ${CMAKE_CURRENT_SOURCE_DIR}/shell/random.c
  ${CMAKE_CURRENT_SOURCE_DIR}/shell/shell_common.c
  ${CMAKE_CURRENT_SOURCE_DIR}/shell/sigisemptyset.c
  ${CMAKE_CURRENT_SOURCE_DIR}/sysklogd/klogd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/sysklogd/logread.c
  ${CMAKE_CURRENT_SOURCE_DIR}/sysklogd/syslogd_and_logger.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/acpid.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/blkdiscard.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/blkid.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/blockdev.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/cal.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/chrt.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/dmesg.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/eject.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/fallocate.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/fatattr.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/fbset.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/fdformat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/fdisk.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/findfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/flock.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/freeramdisk.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/fsck_minix.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/fsfreeze.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/fstrim.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/getopt.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/hexdump.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/hexdump_xxd.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/hwclock.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/ionice.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/ipcrm.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/ipcs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/losetup.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/lspci.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/lsusb.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/mesg.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/mkfs_ext2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/mkswap.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/more.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/mount.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/mountpoint.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/nsenter.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/pivot_root.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/rdate.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/rdev.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/readprofile.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/renice.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/rev.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/rtcwake.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/script.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/scriptreplay.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/setpriv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/setsid.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/swaponoff.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/switch_root.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/uevent.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/umount.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/unshare.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/bcache.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/btrfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/cramfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/erofs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/exfat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/ext.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/f2fs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/fat.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/get_devname.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/hfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/iso9660.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/jfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/lfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/linux_raid.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/linux_swap.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/luks.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/minix.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/nilfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/ntfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/ocfs2.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/reiserfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/romfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/squashfs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/sysv.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/ubifs.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/udf.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/util.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/volume_id.c
  ${CMAKE_CURRENT_SOURCE_DIR}/util-linux/volume_id/xfs.c
)
